# use the official Bun image
# see all versions at https://hub.docker.com/r/oven/bun/tags
FROM oven/bun:1 as base
WORKDIR /usr/src/app

# install all dependencies
FROM base AS install
COPY . .
RUN bun install --ignore-scripts

ENV NODE_ENV=production

RUN cd /usr/src/app/apps/web && bun run build
# RUN cd /usr/src/app/apps/worker/dist && bun run index.js

# copy production dependencies and source code into final image
FROM base AS release
COPY --from=install /usr/src/app/apps/web/.next/standalone .
# COPY --from=install /usr/src/app/apps/web/package.json .

# run the app
ENV PORT=3000
USER bun
EXPOSE 3000/tcp
ENTRYPOINT [ "bun", "run", "server.js" ]
